PRINT 'RUN V2.xml';
BEGIN TRY
CREATE TABLE AD_FCCONFIG (
                CODCONFIG INT NOT NULL IDENTITY(1,1),
                CLIENT_ID VARCHAR(200),
                CLIENT_SECRET VARCHAR(500),
                SCOPE VARCHAR(200),
                SUBSCRIPTION_KEY VARCHAR(100),
                SUBSCRIPTION_KEY_DISTRIBUTION VARCHAR(100),
                SUBSCRIPTION_KEY_CONSUMPTION VARCHAR(100),
                BASE_URL VARCHAR(300),
                AUTH_URL VARCHAR(300),
                CODTIPOPER INT,
                CODLOCAL INT,
                NUTAB INT,
                CODNAT INT,
                CODCENCUS INT,
                CODVEND_PADRAO INT,
                PRICE_TABLE_TIPOS VARCHAR(100),
                PRICE_TABLE_IDS VARCHAR(200),
                CODEMP SMALLINT,
                RESELLER_ID VARCHAR(100),
                STORAGE_ID VARCHAR(100),
                TIPNEG INT,
                TOP_PEDIDO INT,
                CODPARC_PADRAO INT,
                TIMEOUT_MS INT DEFAULT 30000,
                INTERVAL_ORDERS SMALLINT DEFAULT 5,
                INTERVAL_QUEUE SMALLINT DEFAULT 2,
                LOG_RETENTION_DAYS SMALLINT DEFAULT 30,
                MAX_RETRIES SMALLINT DEFAULT 3,
                ATIVO CHAR(1) DEFAULT 'S',
                BATCH_SIZE SMALLINT DEFAULT 50,
                MAX_REQUESTS_MIN SMALLINT DEFAULT 30,
                LAST_ORDER_SYNC DATETIME2,
                LAST_PRODUCT_SYNC DATETIME2,
                LAST_STOCK_SYNC DATETIME2,
                LAST_PRICE_SYNC DATETIME2,
                UI_SOURCE_DEFAULT SMALLINT,
                UI_ENABLE_SOURCE_2 CHAR(1) DEFAULT 'N',
                UI_ENABLE_SOURCE_3 CHAR(1) DEFAULT 'N',
                DH_CRIACAO DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                DH_ALTERACAO DATETIME2,
                CONSTRAINT PK_AD_FCCONFIG PRIMARY KEY (CODCONFIG)
            )
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE TABLE AD_FCQUEUE (
                IDQUEUE INT NOT NULL IDENTITY(1,1),
                ENTITY_TYPE VARCHAR(30) NOT NULL,
                OPERATION VARCHAR(20) NOT NULL,
                ENTITY_ID INT,
                ENTITY_KEY VARCHAR(100),
                PAYLOAD NVARCHAR(MAX),
                STATUS VARCHAR(20) DEFAULT 'PENDENTE',
                RETRY_COUNT SMALLINT DEFAULT 0,
                LAST_ERROR VARCHAR(4000),
                PRIORITY SMALLINT DEFAULT 0,
                DH_CRIACAO DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                DH_PROCESSAMENTO DATETIME2,
                DH_ALTERACAO DATETIME2,
                CONSTRAINT PK_AD_FCQUEUE PRIMARY KEY (IDQUEUE)
            )
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE INDEX IDX_FCQUEUE_STATUS ON AD_FCQUEUE (STATUS, PRIORITY DESC, DH_CRIACAO)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE TABLE AD_FCDEPARA (
                IDDEPARA INT NOT NULL IDENTITY(1,1),
                TIPO_ENTIDADE VARCHAR(30) NOT NULL,
                COD_SANKHYA INT NOT NULL,
                COD_EXTERNO VARCHAR(100) NOT NULL,
                DH_CRIACAO DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                DH_ALTERACAO DATETIME2,
                CONSTRAINT PK_AD_FCDEPARA PRIMARY KEY (IDDEPARA),
                CONSTRAINT UK_FCDEPARA_TIPO_SKW UNIQUE (TIPO_ENTIDADE, COD_SANKHYA)
            )
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE INDEX IDX_FCDEPARA_EXT ON AD_FCDEPARA (TIPO_ENTIDADE, COD_EXTERNO)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE TABLE AD_FCPEDIDO (
                IDPEDIDO INT NOT NULL IDENTITY(1,1),
                ORDER_ID VARCHAR(100) NOT NULL,
                NUNOTA INT NOT NULL,
                CODPARC INT,
                STATUS_FC SMALLINT,
                STATUS_SKW VARCHAR(5),
                STATUS_IMPORT VARCHAR(20),
                VALOR_TOTAL DECIMAL(18,2),
                DH_PEDIDO DATETIME2,
                NOME_CLIENTE VARCHAR(200),
                CPF_CNPJ VARCHAR(20),
                VALOR_FRETE DECIMAL(18,2),
                ERRO_MSG VARCHAR(1000),
                DH_IMPORTACAO DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                DH_FATURAMENTO DATETIME2,
                DH_ENTREGA DATETIME2,
                NF_NUMERO VARCHAR(20),
                NF_SERIE VARCHAR(5),
                NF_CHAVE VARCHAR(60),
                TRACKING_CODE VARCHAR(50),
                OBSERVACAO VARCHAR(500),
                CONSTRAINT PK_AD_FCPEDIDO PRIMARY KEY (IDPEDIDO),
                CONSTRAINT UK_FCPEDIDO_ORDERID UNIQUE (ORDER_ID)
            )
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE INDEX IDX_FCPEDIDO_NUNOTA ON AD_FCPEDIDO (NUNOTA)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE TABLE AD_FCLOG (
                IDLOG INT NOT NULL IDENTITY(1,1),
                NIVEL VARCHAR(20),
                OPERACAO VARCHAR(50),
                MENSAGEM VARCHAR(500),
                REFERENCIA VARCHAR(100),
                DETALHES NVARCHAR(MAX),
                DH_REGISTRO DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                DH_LOG DATETIME2 DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT PK_AD_FCLOG PRIMARY KEY (IDLOG)
            )
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V2.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_DH ON AD_FCLOG (DH_LOG DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD STATUS_IMPORT VARCHAR(20)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD VALOR_TOTAL DECIMAL(18,2)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD DH_PEDIDO DATETIME2
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD NOME_CLIENTE VARCHAR(200)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD CPF_CNPJ VARCHAR(20)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD VALOR_FRETE DECIMAL(18,2)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD ERRO_MSG VARCHAR(1000)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
ALTER TABLE AD_FCLOG ADD DH_LOG DATETIME2 DEFAULT CURRENT_TIMESTAMP
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V3.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_DH_LOG ON AD_FCLOG (DH_LOG DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V4.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD SYNC_STATUS_ENABLED CHAR(1) DEFAULT 'N'
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V4.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD SANKHYA_SERVER_URL VARCHAR(300)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V4.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD SANKHYA_USER VARCHAR(100)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V4.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD SANKHYA_PASSWORD VARCHAR(200)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD STATUS_IMPORT VARCHAR(20)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD VALOR_TOTAL DECIMAL(18,2)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD DH_PEDIDO DATETIME2
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD NOME_CLIENTE VARCHAR(200)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD CPF_CNPJ VARCHAR(20)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD VALOR_FRETE DECIMAL(18,2)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V5.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ADD ERRO_MSG VARCHAR(1000)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V6.xml';
BEGIN TRY
ALTER TABLE AD_FCLOG ADD DH_LOG DATETIME2 DEFAULT CURRENT_TIMESTAMP
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V6.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_DH ON AD_FCLOG (DH_LOG DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V6.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD CODNAT INT
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V6.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD CODCENCUS INT
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V6.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD CODVEND_PADRAO INT
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V7.xml';
BEGIN TRY
ALTER TABLE AD_FCPEDIDO ALTER COLUMN NUNOTA INT NULL
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V7.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD UI_SOURCE_DEFAULT SMALLINT
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V7.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD UI_ENABLE_SOURCE_2 CHAR(1) DEFAULT 'N'
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V7.xml';
BEGIN TRY
ALTER TABLE AD_FCCONFIG ADD UI_ENABLE_SOURCE_3 CHAR(1) DEFAULT 'N'
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V8.xml';
BEGIN TRY
ALTER TABLE AD_FCDEPARA ADD INTEGRA_AUTO CHAR(1) DEFAULT 'N'
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V9.xml';
BEGIN TRY
CREATE INDEX IDX_FCQUEUE_ENTITYKEY_DH ON AD_FCQUEUE (ENTITY_TYPE, ENTITY_KEY, DH_CRIACAO DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V9.xml';
BEGIN TRY
CREATE INDEX IDX_FCQUEUE_ETYPE_STATUS_DH ON AD_FCQUEUE (ENTITY_TYPE, STATUS, DH_CRIACAO DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V9.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_OP_REF_DHREG ON AD_FCLOG (OPERACAO, REFERENCIA, DH_REGISTRO DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V9.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_OP_DHLOG ON AD_FCLOG (OPERACAO, DH_LOG DESC)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V11.xml';
BEGIN TRY
CREATE INDEX IDX_FCPEDIDO_ORDER_STATUS ON AD_FCPEDIDO (ORDER_ID, STATUS_IMPORT, NUNOTA)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V11.xml';
BEGIN TRY
CREATE INDEX IDX_FCPEDIDO_IMPORT_DH ON AD_FCPEDIDO (STATUS_IMPORT, DH_IMPORTACAO)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;

PRINT 'RUN V11.xml';
BEGIN TRY
CREATE INDEX IDX_FCLOG_DH ON AD_FCLOG (DH_LOG)
END TRY BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;


