-- Add missing columns to AD_FCPEDIDO (SQL Server)
IF COL_LENGTH('AD_FCPEDIDO', 'STATUS_IMPORT') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD STATUS_IMPORT VARCHAR(20);

IF COL_LENGTH('AD_FCPEDIDO', 'VALOR_TOTAL') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD VALOR_TOTAL DECIMAL(18,2);

IF COL_LENGTH('AD_FCPEDIDO', 'DH_PEDIDO') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD DH_PEDIDO DATETIME2;

IF COL_LENGTH('AD_FCPEDIDO', 'NOME_CLIENTE') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD NOME_CLIENTE VARCHAR(200);

IF COL_LENGTH('AD_FCPEDIDO', 'CPF_CNPJ') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD CPF_CNPJ VARCHAR(20);

IF COL_LENGTH('AD_FCPEDIDO', 'VALOR_FRETE') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD VALOR_FRETE DECIMAL(18,2);

IF COL_LENGTH('AD_FCPEDIDO', 'ERRO_MSG') IS NULL
    ALTER TABLE AD_FCPEDIDO ADD ERRO_MSG VARCHAR(1000);
