-- Add missing DH_LOG column to AD_FCLOG (SQL Server)
IF COL_LENGTH('AD_FCLOG', 'DH_LOG') IS NULL
    ALTER TABLE AD_FCLOG ADD DH_LOG DATETIME2 DEFAULT CURRENT_TIMESTAMP;

-- Backfill from DH_REGISTRO when available
IF COL_LENGTH('AD_FCLOG', 'DH_REGISTRO') IS NOT NULL
    UPDATE AD_FCLOG SET DH_LOG = DH_REGISTRO WHERE DH_LOG IS NULL;

-- Rebuild index for DH_LOG
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_FCLOG_DH' AND object_id = OBJECT_ID('AD_FCLOG'))
    DROP INDEX IDX_FCLOG_DH ON AD_FCLOG;

CREATE INDEX IDX_FCLOG_DH ON AD_FCLOG (DH_LOG DESC);
